### PR TITLE
File Upload

### PR DESCRIPTION
**Pull request by ameiyappan-gh**

### CODE REVIEW

**Comment by ameiyappan-gh** [comment]
Hey, I am unsure what this

**Comment by ameiyappan-gh** [comment]
Hey, I am unsure what the misplaced CSV means, all my files look to be in the right locations and seem to be named correctly.
I would appreciate any help regarding this issue

**Comment by biggs1430** [comment]
Hi, it looks like you have a different model name between the forecast and the metadata file.  The subdirectory is GH-FluSight, but the metadata file is named GHflusight-model. I think if you rename the metadata file to metadata-GH-FluSight, it could correct the error.

**Comment by ameiyappan-gh** [comment]
Ok thank you!

**Pull request closed without merging**
