### PR TITLE
SigSci 2022-02-14 forecast submission (SigSci-CREG and SigSci-TSENS)

### PR DESCRIPTION
**Pull request by vpnagraj**

### CODE REVIEW

**Comment by vpnagraj** [comment]
submission from multiple models is intentional ... SigSci-CREG is "primary" and SigSci-TSENS is "secondary"

thanks!

**Comment by pragatiprasadf6** [comment]
Hi - if possible, can you submit each model in a separate pull request next time?

**Comment by vpnagraj** [comment]
@pragatiprasadf6 thank you for merging this week. we'll plan to submit separate PRs for each of our models moving forward.

**Comment by pragatiprasadf6** [comment]
> @pragatiprasadf6 thank you for merging this week. we'll plan to submit separate PRs for each of our models moving forward.

thank you!

**Pull request merged**
